### ISSUE TITLE
Unable to create SSL connection for PostgreSQL

### ISSUE THREAD

**Issue by edewata** [dogtagpki/jss#610] opened 2020-07-28 00:47 UTC
JSS fails to establish an SSL connection for PostgreSQL. This may be required by PKI ACME in certain environments. If the SSL mode is disabled, the PostgreSQL connection can be established properly without SSL.

Steps to reproduce:
1. Install PKI 10.9, JSS 4.7, and PostgreSQL JDBC 42.2.8.
2. Prepare a PostgreSQL database that supports SSL.
3. Install PKI ACME (https://github.com/dogtagpki/pki/blob/master/docs/installation/acme/Installing_ACME_Responder.md) with the following database.conf:
```
class=org.dogtagpki.acme.database.PostgreSQLDatabase
password=<password>
url=jdbc:postgresql://<server>:5432/<database>
user=<username>
```
4. Execute an operation that uses database connection, e.g.:
```
$ certbot certonly --standalone -d $HOSTNAME \
    --server http://$HOSTNAME:8080/acme/directory \
    --register-unsafely-without-email \
    --agree-tos
```
5. Disable SSL by adding the following parameter into database.conf:
```
sslmode=disable
```
6. Restart the server and rerun the same command.

Actual result: The operation in step 4 failed, but the same operation in step 6 succeeded.

Expected result: Both operations in step 4 and 6 should succeed.

Additional info: In step 4 the ACME debug log will have the following error messages:
```
2020-07-28 02:06:14 [http-nio-8080-exec-2] INFO: Connecting to jdbc:postgresql://<server>:5432/<database>
2020-07-28 02:06:15 [http-nio-8080-exec-2] SEVERE: Servlet.service() for servlet [ACME] in context with path [/acme] threw exception
org.jboss.resteasy.spi.UnhandledException: org.postgresql.util.PSQLException: SSL error: Unable to unwrap data using SSLEngine: Error duing SSL.ForceHandshake() :: SSL_ERROR_INAPPROPRIATE_FALLBACK_ALERT (-12157)
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:78)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:422)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:225)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: SSL error: Unable to unwrap data using SSLEngine: Error duing SSL.ForceHandshake() :: SSL_ERROR_INAPPROPRIATE_FALLBACK_ALERT (-12157)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:42)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:441)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:94)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.dogtagpki.acme.database.PostgreSQLDatabase.connect(PostgreSQLDatabase.java:95)
	at org.dogtagpki.acme.database.PostgreSQLDatabase.addNonce(PostgreSQLDatabase.java:195)
	at org.dogtagpki.acme.server.ACMEEngine.createNonce(ACMEEngine.java:485)
	at org.dogtagpki.acme.server.ACMENewNonceService.createNonce(ACMENewNonceService.java:52)
	at org.dogtagpki.acme.server.ACMENewNonceService.headNewNonce(ACMENewNonceService.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
	... 55 more
Caused by: java.io.IOException: Unable to unwrap data using SSLEngine: Error duing SSL.ForceHandshake() :: SSL_ERROR_INAPPROPRIATE_FALLBACK_ALERT (-12157)
	at org.mozilla.jss.ssl.javax.JSSSocketChannel.read(JSSSocketChannel.java:286)
	at java.nio.channels.SocketChannel.read(SocketChannel.java:481)
	at org.mozilla.jss.ssl.javax.JSSSocketChannel.read(JSSSocketChannel.java:237)
	at org.mozilla.jss.ssl.javax.JSSSocketChannel.finishConnect(JSSSocketChannel.java:149)
	at org.mozilla.jss.ssl.javax.JSSSocket.doHandshake(JSSSocket.java:277)
	at org.mozilla.jss.ssl.javax.JSSSocket.startHandshake(JSSSocket.java:425)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:40)
	... 78 more
Caused by: javax.net.ssl.SSLHandshakeException: Error duing SSL.ForceHandshake() :: SSL_ERROR_INAPPROPRIATE_FALLBACK_ALERT (-12157)
	at org.mozilla.jss.ssl.javax.JSSEngineReferenceImpl.updateHandshakeState(JSSEngineReferenceImpl.java:857)
	at org.mozilla.jss.ssl.javax.JSSEngineReferenceImpl.unwrap(JSSEngineReferenceImpl.java:1036)
	at org.mozilla.jss.ssl.javax.JSSSocketChannel.read(JSSSocketChannel.java:268)
	... 84 more
```

The stack trace points to the following code in PostgreSQL JDBC:
https://github.com/pgjdbc/pgjdbc/blob/REL42.2.8/pgjdbc/src/main/java/org/postgresql/ssl/MakeSSL.java#L40

**Comment by cipherboy** [comment] 2020-07-28 12:36
@edewata Are you able to send me a packet capture of the handshake by any chance? :-)

**Comment by cipherboy** [comment] 2020-07-28 14:23
This is happening because the server supports TLSv1.3 but your client only supports TLSv1.2.

From the packet capture:

![Screenshot from 2020-07-28 10-17-21](https://user-images.githubusercontent.com/914030/88677636-8bbb6f80-d0bb-11ea-8cec-ea1829231650.png)

You can see your client (this SSLEngine) advertises TLSv1.2 support with [`TLS_FALLBACK_SCSV`](https://tools.ietf.org/html/rfc7507). This is good, because it prevents protocol downgrade attacks.

The server responds:

![Screenshot from 2020-07-28 10-18-22](https://user-images.githubusercontent.com/914030/88677772-b0afe280-d0bb-11ea-831a-4ad3d56015f0.png)

Per section 3 of above RFC, this means the server supports a higher TLS version than you do (TLSv1.3). You have two options:

1. Upgrade NSS to a version that supports TLSv1.3. This exists on _supported_ Fedora versions (F31+) and will land in RHEL 8.3 as well. Per IRC, you're running `nss-3.51.1-1.fc30.x86_64`.
2. Don't use [downgrade protection](https://github.com/dogtagpki/jss/blob/master/org/mozilla/jss/ssl/javax/JSSEngine.java#L948). Perhaps you could submit a PR to make that a static configuration and add options for disabling it, so when a new `SSLEngine` instance gets created, you'd inherit the static configuration's current options and it'd be disabled.

**Comment by edewata** [comment] 2020-07-28 20:30
I tried NSS 3.54.0 from this repo, but I'm still getting the same error message:
https://copr.fedorainfracloud.org/coprs/edewata/acme/builds/

**Comment by edewata** [comment] 2020-07-28 21:19
I tried disabling `ENABLE_FALLBACK_SCSV` in JSS, now I'm getting this error:
```
2020-07-28 16:08:26 [http-nio-8080-exec-2] INFO: Connecting to jdbc:postgresql://<server>:5432/<database>
2020-07-28 16:08:26 [http-nio-8080-exec-2] SEVERE: Servlet.service() for servlet [ACME] in context with path [/acme] threw exception
org.jboss.resteasy.spi.UnhandledException: org.postgresql.util.PSQLException: Protocol error.  Session setup failed.
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:78)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:422)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:225)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: Protocol error.  Session setup failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:707)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.dogtagpki.acme.database.PostgreSQLDatabase.connect(PostgreSQLDatabase.java:94)
	at org.dogtagpki.acme.database.PostgreSQLDatabase.addNonce(PostgreSQLDatabase.java:194)
	at org.dogtagpki.acme.server.ACMEEngine.createNonce(ACMEEngine.java:493)
	at org.dogtagpki.acme.server.ACMENewNonceService.createNonce(ACMENewNonceService.java:52)
	at org.dogtagpki.acme.server.ACMENewNonceService.headNewNonce(ACMENewNonceService.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
	... 55 more
```
The stack trace points to the following code in PostgreSQL JDBC:
https://github.com/pgjdbc/pgjdbc/blob/REL42.2.8/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L707

I'm guessing the SSL handshake wasn't completed properly, so the data gets corrupted causing a PSQL protocol error.

**Comment by edewata** [comment] 2020-07-28 21:27
One possible workaround is to not install JSS as the default SSL context, so applications will use JSSE by default, but PKI will need to be modified to specifically use JSS context.

**Comment by cipherboy** [comment] 2020-09-02 16:31
The original error in question (`SSL_ERROR_INAPPROPRIATE_FALLBACK_ALERT`) should now be fixed on `v4.7.x` and `master` branches. @edewata -- could you retest and close this issue if the issue is fixed?

**Comment by fmarco76** [comment] 2022-12-23 18:12
@cipherboy and @edewata I have just tested the connection with postgreql (lastest version available on dockerhub) with the master and it works as expected:

```
[root@pki acme]# certbot certonly --standalone -d pki.example.com --server http://pki.example.com:8080/acme/directory --register-unsafely-without-email  --agree-tos
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for pki.example.com

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/pki.example.com/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/pki.example.com/privkey.pem
This certificate expires on 2023-03-23.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[root@pki acme]# cat database.conf 
class=org.dogtagpki.acme.database.PostgreSQLDatabase
password=myPassword
url=jdbc:postgresql://postgres.example.com:5432/postgres
user=postgres
```

I am closing this issue but if you have additional issue feel free to open again. 

@edewata should we have to add a CI test for the postgresql case?

**Closed by fmarco76** 2022-12-23 18:12 UTC

**Comment by edewata** [comment] 2023-01-03 06:28
@cipherboy @fmarco76 Thanks! Sorry, I did not have a chance to retest this. Yes, if you have time, it would be nice to have a CI test for SSL connection to PostgreSQL to make sure that JSS is compatible with third-party applications.
