### ISSUE TITLE
Add in missing annotations

### ISSUE THREAD

**Issue by ckelleyRH** [dogtagpki/jss#705] opened 2021-05-21 10:08 UTC
Deprecated methods should be annotated so they can be easily identified and removed later.
Overridden methods should be annotated to benefit from compile-time checking of interface contracts.

**Comment by cipherboy** [comment] 2021-05-21 11:44
@ckelleyRH Just a heads up, you've added the "Resolves:" keyword to all of the above PRs.. Maybe "related to" works better as they all need to merge before the issue is resolved (and presently the first PR merged will close this issue). Doesn't really matter this time as you've opened all the PRs right away, but for any other efforts, something to know for the future :)

**Closed** 2021-05-21 14:39 UTC

**Comment by ckelleyRH** [comment] 2021-05-21 14:45
@cipherboy Ah I see, thanks for the tip!
